DROP TABLE `PRMNGSYS`.`T_CONSTURCT_DEP_INFO`;
CREATE TABLE IF NOT EXISTS `PRMNGSYS`.`T_CONSTURCT_DEP_INFO` (
  `dep_code` VARCHAR(10) NOT NULL COMMENT '施工单位编号',
  `dep_nm` VARCHAR(400) NULL DEFAULT NULL COMMENT '施工单位名称',
  `dep_linkman` VARCHAR(400) NULL DEFAULT NULL COMMENT '施工单位联系人',
  `input_time` VARCHAR(8) NULL DEFAULT NULL COMMENT '录入时间',
  `input_man` VARCHAR(10) NULL DEFAULT NULL COMMENT '录入人',
  PRIMARY KEY (`dep_code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '施工单位信息表';
