DROP TABLE `PRMNGSYS`.`T_COMM_DICT`;
CREATE TABLE IF NOT EXISTS `PRMNGSYS`.`T_COMM_DICT` (
  `dict_type` VARCHAR(5) NOT NULL COMMENT '字典类型',
  `dict_code` VARCHAR(5) NOT NULL COMMENT '字典编码',
  `dict_des` VARCHAR(400) NULL DEFAULT NULL COMMENT '字典描述',
  `dict_val` VARCHAR(400) NULL DEFAULT NULL COMMENT '字典值',
  PRIMARY KEY (`dict_type`, `dict_code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '公共字典表';
