DROP TABLE `PRMNGSYS`.`T_CUS_PRJ_INFO`;
CREATE TABLE IF NOT EXISTS `PRMNGSYS`.`T_CUS_PRJ_INFO` (
  `appr_code` VARCHAR(14) NOT NULL COMMENT '审批编号',
  `sub_emp_code` VARCHAR(10) NULL DEFAULT NULL COMMENT '提交人编号',
  `mng_emp_code` VARCHAR(10) NULL DEFAULT NULL COMMENT '客户经理编号',
  `agt_com_code` VARCHAR(10) NULL DEFAULT NULL COMMENT '代理公司编号',
  `prj_nm` VARCHAR(40) NULL DEFAULT NULL COMMENT '项目名称',
  `prj_adr` VARCHAR(400) NULL DEFAULT NULL COMMENT '项目详细地址',
  `remark` VARCHAR(400) NULL DEFAULT NULL COMMENT '备注',
  `buss_nature` VARCHAR(5) NULL DEFAULT NULL COMMENT '业务性质',
  `buss_type` VARCHAR(5) NULL DEFAULT NULL COMMENT '业务类型',
  `voice_usr_cnt` INT(11) NULL DEFAULT NULL COMMENT '语音用户覆盖数',
  `voice_port_cnt` INT(11) NULL DEFAULT NULL COMMENT '语音设备端口数量(预计发展用户数)',
  `data_demand_type` VARCHAR(5) NULL DEFAULT NULL COMMENT '数据需求',
  `bandwidth` VARCHAR(5) NULL DEFAULT NULL COMMENT '带宽',
  `amt` INT(11) NULL DEFAULT NULL COMMENT '数量',
  `strt_site` VARCHAR(400) NULL DEFAULT NULL COMMENT '起始地点',
  `ICT_demand` VARCHAR(45) NULL DEFAULT NULL COMMENT 'ICT需求',
  `prg_rnd_net_use_type` VARCHAR(5) NULL DEFAULT NULL COMMENT '该项目周边接入网机房情况',
  `prop_access_type` VARCHAR(5) NULL DEFAULT NULL COMMENT '建议接入方式',
  `unicom_invst_scope` VARCHAR(5) NULL DEFAULT NULL COMMENT '联通投资范围',
  `sign` VARCHAR(400) NULL DEFAULT NULL COMMENT '签字',
  `sign_date` VARCHAR(8) NULL DEFAULT NULL COMMENT '日期',
  `is_access` VARCHAR(5) NULL DEFAULT NULL COMMENT '能否接入',
  `join_up_type` VARCHAR(45) NULL DEFAULT NULL COMMENT '接入方式',
  `join_up_area` VARCHAR(400) NULL DEFAULT NULL COMMENT '接入区域',
  `join_up_room` VARCHAR(400) NULL DEFAULT NULL COMMENT '接入机房',
  `join_up_room_type` VARCHAR(5) NULL DEFAULT NULL COMMENT '接入机房性质',
  `route_build_cycle` INT(11) NULL DEFAULT NULL COMMENT '线路建设周期',
  `voice_plan_type` VARCHAR(5) NULL DEFAULT NULL COMMENT '语音方案',
  `data_plan_type` VARCHAR(5) NULL DEFAULT NULL COMMENT '数据方案',
  `trans_type` VARCHAR(5) NULL DEFAULT NULL COMMENT '传输方案',
  `station_net_plan_type` VARCHAR(5) NULL DEFAULT NULL COMMENT '驻地网方案（备注：新建小区，慎重投资建设）',
  `is_pen_res_exam` VARCHAR(5) NULL DEFAULT NULL COMMENT '铅芯资源核查',
  `pen_maintain_adv` VARCHAR(400) NULL DEFAULT NULL COMMENT '维护建议',
  `is_exist_elec` VARCHAR(5) NULL DEFAULT NULL COMMENT '是否有电路资源',
  `elec_maitain_adv` VARCHAR(400) NULL DEFAULT NULL,
  `prg_build_cycle` INT(11) NULL DEFAULT NULL COMMENT '项目建设周期',
  PRIMARY KEY (`appr_code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '客户接入项目信息表';
