DROP TABLE `PRMNGSYS`.`T_DEP_INFO`;
CREATE TABLE IF NOT EXISTS `PRMNGSYS`.`T_DEP_INFO` (
  `dep_code` VARCHAR(10) NOT NULL COMMENT '部门编号',
  `dep_nm` VARCHAR(400) NULL DEFAULT NULL COMMENT '部门名',
  `dep_quantity` INT(11) NULL DEFAULT NULL COMMENT '部门人数',
  `dep_leader_code` VARCHAR(10) NULL DEFAULT NULL COMMENT '部门领导',
  PRIMARY KEY (`dep_code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '部门信息表';
